# Generated by Django 3.2.3 on 2021-05-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes', models.TextField()),
                ('roomName', models.CharField(max_length=100)),
            ],
        ),
    ]
