# Generated by Django 3.2.3 on 2021-05-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210529_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='colorFlag',
            field=models.BooleanField(default=False),
        ),
    ]
