# Generated by Django 3.2.3 on 2021-05-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_board_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='redPlayer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='board',
            name='yellowPlayer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
